# Generated by Django 4.2.11 on 2024-04-02 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('file_text', models.FileField(upload_to='')),
                ('file_img', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
                ('genre', models.CharField(max_length=40)),
                ('release_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=120)),
                ('is_author', models.BooleanField(default=False)),
                ('balance', models.IntegerField()),
                ('created_book', models.ManyToManyField(related_name='created_book', to='app_add_book.book')),
                ('my_book', models.ManyToManyField(related_name='my_book', to='app_add_book.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
