# Generated by Django 5.0.3 on 2024-03-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main_menu', '0004_rename__author_book_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='auth',
        ),
        migrations.DeleteModel(
            name='author',
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
